version: 2
jobs:
  build_library:
    docker:
      - image: circleci/node:12.9.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
      - save_cache:
          name: Save Cache
          paths:
            - components/node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Prettier Check
          command: |
            yarn prettier:check
      - run:
          name: Lint
          command: |
            yarn lint
      - run:
          name: Test
          command: |
            yarn test:ci
      - run:
          name: Build
          command: |
            yarn build
      - run:
          name: Test Artifacts
          command: |
            yarn test:artifacts
